name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ecr_url: 677931183417.dkr.ecr.ap-northeast-2.amazonaws.com/reactsample
  role_arn: arn:aws:iam::677931183417:role/github-action
  aws_region: ap-northeast-2


jobs:
  build:

    runs-on: self-hosted

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    outputs:
      tag_date: ${{ steps.tag.outputs.date }}
      tag_git_hash: ${{ steps.tag.outputs.git_hash }}

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2
    - name: Set up node.js 16.10.0
      uses: actions/setup-node@v2 
      with:
        node-version: 16.10.0
        cache: 'npm'
        path: ~/.npm
    # - name: clean cache
    # run: npm cache clean --force
    - name: Install dependencies
      run: npm install -g n
    # - runs: npm run test:e2e

    - name: Docker build reactsample
      run: docker build -t reactsample ./

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ env.aws_region }}
        role-session-name: GitHubActions
        role-to-assume: ${{ env.role_arn }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Publish Image to ECR(reactsample)
      run: |
          docker tag reactsample:latest 677931183417.dkr.ecr.ap-northeast-2.amazonaws.com/reactsample:latest
          docker push 677931183417.dkr.ecr.ap-northeast-2.amazonaws.com/reactsample:latest

    # 도커 Hub 로그인
    #- name: Login Dockerhub
    #  env:
    #    DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    #    DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
    #  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      

    # Docker 이미지 빌드
    #- name: Build the Docker image
    #  run: docker build -t iesay .
    # 이미지 태깅
    #- name: taging
    #  run: docker tag iesay:latest kopi2642/iesay:latest 
    # Dockerhub에 푸시 
    #- name: Push to Dockerhub
    #  run: docker push kopi2642/iesay:latest
