name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Set up node.js 18.16.1
      uses: actions/setup-node@v3 
      with:
        node-version: 18.16.1
        cache: 'npm'
    - name: npm cache verify
      run: npm cache verify
    - name: Install dependencies
      run: npm install
    # - runs: npm run test:e2e

    # 도커 Hub 로그인
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      

    # Docker 이미지 빌드
    - name: Build the Docker image
      run: docker build -t iesay .
    # 이미지 태깅
    - name: taging
      run: docker tag iesay:latest kopi2642/iesay:latest 
    # Dockerhub에 푸시 
    - name: Push to Dockerhub
      run: docker push kopi2642/iesay:latest 
