name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#env:
  #ecr_url: 238853424118.dkr.ecr.ap-northeast-2.amazonaws.com/reactsample
  #role_arn: arn:aws:iam::238853424118:role/github-role
  #aws_region: ap-northeast-2


jobs:
  build:

    runs-on: self-hosted
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: arn:aws:iam::238853424118:role/github-action-s3
         aws-region: ap-northeast-2   
 
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/

          
 

    # 도커 Hub 로그인
    #- name: Login Dockerhub
    #  env:
    #    DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    #    DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
    #  run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      

    # Docker 이미지 빌드
    #- name: Build the Docker image
    #  run: docker build -t iesay .
    # 이미지 태깅
    #- name: taging
    #  run: docker tag iesay:latest kopi2642/iesay:latest 
    # Dockerhub에 푸시 
    #- name: Push to Dockerhub
    #  run: docker push kopi2642/iesay:latest 
